# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Codegaze
tagline:             Thanos K
url:                 https://codegaze.github.io
# paginate:            1
baseurl:             ""


# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


exclude: ["_dev",
          "gulpfile.js",
          "node_modules",
          "package.json"]
