# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

permalink: /:year/:month/:day/:title/

# Setup
title:               CodegazeRants
tagline:             Thanos Kolovos
url:                 https://codegazerants.com
# paginate:            1
baseurl:             ""


# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


exclude: ["_dev",
          "gulpfile.js",
          "node_modules",
          "package.json"]
